version: '3.7'

services:
  foo_clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "18123:8123"
      - "19000:9000"
    ulimits:
      nofile:
        soft: "262144"
        hard: "262144"
    environment:
      - CLICKHOUSE_DB=my_database 
      - CLICKHOUSE_USER=username 
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1 
      - CLICKHOUSE_PASSWORD=password
    volumes:
      - clickhouse_db:/var/lib/clickhouse

volumes:
  clickhouse_db: