_101:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: irib-rhoq
      dataset: "{{ env_var('DEVELOPER_PREFIX') }}"
      threads: 4
      timeout_seconds: 300
      priority: interactive
      fixed_retries: 1
    stage:
      type: bigquery
      method: oauth
      project: irib-rhoq
      dataset: "{{ env_var('DEVELOPER_PREFIX') }}"
      threads: 4
      timeout_seconds: 300
      priority: interactive
      fixed_retries: 1
    qa:
      type: bigquery
      method: oauth
      project: irib-rhoq
      dataset: "{{ env_var('DEVELOPER_PREFIX') }}"
      threads: 4
      timeout_seconds: 300
      priority: interactive
      fixed_retries: 1
    prod:
      type: bigquery
      method: service-account
      project: irib-rhoq
      dataset: "{{ env_var('DEVELOPER_PREFIX') }}"
      thread: 4
      keyfile: "{{ env_var('GCLOUD_SERVICE_JSON') }}"
      timeout_seconds: 300
      priority: interactive
      retries: 1
