_101:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: irib-rhoq
      dataset: "{{ env_var('DEVELOPER_PREFIX') }}"
      threads: 4
      timeout_seconds: 300
      priority: interactive
      fixed_retries: 1
    stage:
      type: bigquery
      method: oauth
      project: irib-rhoq
      dataset: "{{ env_var('DEVELOPER_PREFIX') }}"
      threads: 4
      timeout_seconds: 300
      priority: interactive
      fixed_retries: 1
    qa:
      type: bigquery
      method: oauth
      project: irib-rhoq
      dataset: "{{ env_var('DEVELOPER_PREFIX') }}"
      threads: 4
      timeout_seconds: 300
      priority: interactive
      fixed_retries: 1
    prod:
      type: bigquery
      method: service-account
      project: irib-rhoq
      dataset: "{{ env_var('DEVELOPER_PREFIX') }}"
      thread: 4
      keyfile: "{{ env_var('GCLOUD_SERVICE_JSON') }}"
      timeout_seconds: 300
      priority: interactive
      retries: 1
clickhouse:
  target: dev
  fal_extract_load:
    dev:
      my_airbyte_el:
        type: airbyte
        host: http://127.0.0.1:8000
        connections:
          - name: "S3_Example <> Clickhouse"
            id: 4a2b82db-7b95-4c14-ae4c-2de439b270c8
  outputs:
    dev:
      type: clickhouse
      schema: bdmaps
      host: localhost
      port: 18123
      user: username
      password: password
      secure: False
      